### ISSUE TITLE
eval translation

### ISSUE THREAD

**Issue by yuyu0927** [amyxlase/relpose-plus-plus#18]
Hi,

In you training code, normalize_cameras=True, which means T and R are decoupled, am I right? But, in your eval code, when you load GT, normalize_cameras=False (see eval/util.py line25), which means first camera frame is adopted here (SFM format). From my perspective, their formats are inconsistent. I don't really understand here, can you explain a little bit? I really appreciate that!

**Comment by jasonyzhang** [comment]
I am not sure what you mean by T and R are decoupled. The translation and rotations are always predicted independently.

normalize_cameras applies a global transform to a batch of cameras such that the origin is the intersection point of the optical axes and the distance of the first camera to the origin is 1. At evaluation time, we solve a procrustes for the optimal global scale, rotation, and translation. Thus, there is no point in normalizing any cameras since any transformation applied to the cameras would be undone by the procrustes anyway.
