### ISSUE TITLE
Some clarification questions as well as question how to use a custom dataset

### ISSUE THREAD

**Issue by ttsesm** [amyxlase/relpose-plus-plus#3]
Hi,

Congratulations for your work and many thanks for making it public. Since it seemed quite interesting for my project I was really curious to try it and see how it performs for my task. For my project I have a set of images from a turntable of different fragments. In practice for each fragment I have a set of 121 images with a difference of 3 degrees one from the other. For each one of these images I have the corresponding masks as well as the ground truth camera poses: An example can be seen in the images below:
![image](https://github.com/amyxlase/relpose-plus-plus/assets/10189018/706be1fb-035c-494f-998d-68da641f05d2)
![image](https://github.com/amyxlase/relpose-plus-plus/assets/10189018/3a134352-5325-4daf-b7db-436d0f177619)

![image](https://github.com/amyxlase/relpose-plus-plus/assets/10189018/3f36984e-8295-4c94-8a1f-cdc9c33f6e2e)
![image](https://github.com/amyxlase/relpose-plus-plus/assets/10189018/5ce252d2-0f25-41cf-a83b-83b44c98140a)

![image](https://github.com/amyxlase/relpose-plus-plus/assets/10189018/508aeb2c-c829-4691-9286-50dd1bec17e7)

Now the idea is that I would like to extract the camera pose for an unseen view based on the existing ones.

Thus, I was curious to see how your approach performs. For that reason I set up a virtual environment and downloaded the pretrained models/weights and I've run it on a setup of 8 images:
![image](https://github.com/amyxlase/relpose-plus-plus/assets/10189018/3ea509c3-47bf-421f-841c-818389817329)

giving me the following output:
![image](https://github.com/amyxlase/relpose-plus-plus/assets/10189018/72ae05a8-2e84-4cdd-a3d3-2a2500233118)

Which seems to work quite nicely already out of the box. Therefore, I would like to see if I can optimize it so that it works with my dataset. For that I have some questions:

1. I got the aforementioned result by using the masked pre-trained model. I guess the other one is based on the bounding boxes if I am not mistaken, right?
2. As it is the demo script now it resolves the camera pose estimation for a given images between 2-8, can be modified to give an output for only one image or for more than 8. I guess I would need to retrain the model?
3. How can to plot the ground truth camera poses so that I can get a qualitative representation of the error?
4. Do you already have a script to compute the quantitative rotation and translation error in regards to the ground truth camera poses?
5. As I understood you estimate the camera poses in regards to the camera pose of the first image, right? Since from what I've seen the estimated camera pose of the first image is always an identity matrix and then I guess you use the `utils/normalize_cameras.py` script to transform the camera poses back and forth if it is needed.
6. If I wanted to retrain the model for my fragments, would make sense to train for different fragments all together or to train a model for each piece individually?

Thank you for your time.

**Comment by amyxlase** [comment]
Thank you for taking the time to try our demo, and apologies for my delayed response. I have included some code at the end of this reply, and will refer to some of these functions as I address your questions individually.

1. Correct.
2. Since our method computes relative rotations between the cameras, it would not work for just 1 image. For >8 images, you would need to retrain the model. Please note that our method was designed with the sparse-view setting in mind, if you wish to perform inference with a large number of views, other methods such as [hloc](https://github.com/cvg/Hierarchical-Localization) may be more suitable.
3. Our plotly visualization code is available in the demo notebook, if you expand the cell "Plotly Scene Visualization Setup". This code constructs N Pytorch3D cameras for the predicted poses and adds these to a scene dictionary. This scene dictionary is passed as input to an existing Plotly visualization function. To view the ground truth cameras in the same plot as the predicted ones, construct N additional ground truth cameras and include them as additional keys in the scene dictionary. The Pytorch3D function [look_at_view_transform](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html#pytorch3d.renderer.cameras.look_at_view_transform) may be useful if your ground truth poses are represented as azimuths and elevations. It may be necessary to use `compute_optimal_alignment` to align the ground truth and predicted poses.

<img width="274" alt="image" src="https://github.com/amyxlase/relpose-plus-plus/assets/31298710/a36e57a9-85ed-4591-8e47-df77eda8d298">

4. We will release our full evaluation driver at a later time, but `compute_angular_error_batch` can be used to determine rotation error and `get_camera_center_error` should be used to determine camera center error.

5. The function `utils/normalize_cameras.py` simply rescales the scene so that the first camera is unit distance away from the closest point to all optical axes. As our method estimates relative rotations, the first camera rotation need not be identity. More details about this can be found in our paper, or at the video on our [website](https://amyxlase.github.io/relpose-plus-plus/).
6. If you plan to evaluate on fragments not seen at training time, then I would recommend training on as many fragments as possible.

```
def compute_angular_error_batch(rotation1, rotation2):
    """
    Args:
        R1 (torch.Tensor): (N, 3, 3).
        R2 (torch.Tensor): (N, 3, 3).

    Returns:
        error (torch.Tensor): (N)
    """
    R_rel = np.einsum("Bij,Bjk ->Bik", rotation1.transpose(0, 2, 1), rotation2)
    t = (np.trace(R_rel, axis1=1, axis2=2) - 1) / 2
    theta = np.arccos(np.clip(t, -1, 1))
    return theta * 180 / np.pi

# A should be GT, B should be predicted
def compute_optimal_alignment(A, B):
    """
    Compute the optimal scale s, rotation R, and translation t that minimizes:
    || A - (s * B @ R + T) || ^ 2

    Reference: Umeyama (TPAMI 91)

    Args:
        A (torch.Tensor): (N, 3).
        B (torch.Tensor): (N, 3).

    Returns:
        s (float): scale.
        R (torch.Tensor): rotation matrix (3, 3).
        t (torch.Tensor): translation (3,).
    """
    A_bar = A.mean(0)
    B_bar = B.mean(0)
    # normally with R @ B, this would be A @ B.T
    H = (B - B_bar).T @ (A - A_bar)
    U, S, Vh = torch.linalg.svd(H, full_matrices=True)
    s = torch.linalg.det(U @ Vh)
    S_prime = torch.diag(torch.tensor([1, 1, torch.sign(s)], device=A.device))
    variance = torch.sum((B - B_bar) ** 2)
    scale = 1 / variance * torch.trace(torch.diag(S) @ S_prime)
    R = U @ S_prime @ Vh
    t = A_bar - scale * B_bar @ R

    A_hat = scale * B @ R + t
    return A_hat, scale, R, t

def get_camera_center_error(R_pred, T_pred, R_gt, T_gt, gt_scene_scale):
    """
    Args:
        R_pred (torch.Tensor): (N, 3, 3).
        T_pred (torch.Tensor): (N, 3).
        R_gt (torch.Tensor): (N, 3, 3) from any coordinate frame.
        T_gt (torch.Tensor): (N, 3) from any coordinate frame.
        gt_scene_scale (float): distance from intersection of all optical axes to furthest camera.

    Returns:
        error (torch.Tensor): (N)
    """
    cameras_gt = FoVPerspectiveCameras(R=R_gt, T=T_gt)
    cc_gt = cameras_gt.get_camera_center()
    cameras_pred = FoVPerspectiveCameras(R=R_pred, T=T_pred)
    cc_pred = cameras_pred.get_camera_center()

    A_hat, _, _, _ = compute_optimal_alignment(cc_gt, cc_pred)
    norm = torch.linalg.norm(cc_gt - A_hat, dim=1) / gt_scene_scale
    return norm
```

**Comment by ttsesm** [comment]
@amyxlase thanks for the feedback and apologies for my delayed response.

Regarding plotting the ground truth cameras by passing them to the `plotly_scene_visulization()" function I guess I would need to pass them through the `utils/normalize_cameras.py` and the `utils/first_camera_transform()` first, right? so that the first camera is unit distance away from the closest point to all optical axes and the rotation need to be identity, like in the estimated ones? As you do here https://github.com/amyxlase/relpose-plus-plus/blob/3f6413593f00c5750b93db7129d81e91af8fbf5d/relpose/dataset/co3d_v2.py#L323

Also could you elaborate a bit why I will need to run the `compute_optimal_alignment()` function between the ground truth and estimated poses?

Moreover, to what order and format should they be given. From what I've seen it should be a `List[camera]` where camera is a dictionary with the following keys:
```
{
    "filepath": <filepath>, # as a string
    "R": <rotation_matrix>, # as ????
    "T": <translation_matrix>, # as ????
    "focal_length": <focal_length>, # as ???
    "principal_point": <principal_point>, # as ???
    "bbox": bbox, # as list of [xmin, ymin, xmax, ymax] format
}
```
can you elaborate what is the format of the `rotation_matrix`, `translation_matrix` and `focal_length`, `principal_point` respectively. As for the order I guess should be the same as the order of the input images I guess?

Btw, for creating a custom dataset I will need to create a list of dictionaries as the above for each of the training/testing images, right?  Well from the above images you have an idea of my dataset format, where I have the rgb images, the corresponding masks and the ground truth camera poses. In principle I would like to train my model for the custom datast based on this format. I see that you already have a script `relpose/dataset/custom.py`

Sorry for asking all these questions but I do not want to download all the CO3Dv2 dataset.

Thanks.

**Comment by jasonyzhang** [comment]
Re: alignment of ground truth and predicted cameras for visualization. Yes, the ground truth and predicted camera coordinate systems may not be the same even though they could be equally valid. As you said, one option is to use the camera normalization code on the ground truth cameras to set the first camera to have unit translation and place the world origin at the point closest to the intersection of the optical axes.

Another option is to solve for the best possible coordinate system transformation that would align the predicted cameras to the ground truth cameras (this is what we do for evaluation). This may be better because it is agnostic to any assumptions made by the predicted or ground truth coordinate systems.
Here is some code for that:
```
def align_cameras(cameras_gt, cameras_pred):
    cc_pred, s, R, T = compute_optimal_alignment(
        cameras_gt.get_camera_center(), cameras_pred.get_camera_center()
    )
    T = T.unsqueeze(0)

    cameras_new = FoVPerspectiveCameras(
        R=R.T.unsqueeze(0) @ cameras_pred.R,
        T=s * cameras_pred.T - (T @ R.T @ cameras_pred.R).squeeze(1),
    )
    
    if torch.isnan(T).any():
        cameras_new.T = torch.zeros_like(cameras_new.T)
    return cameras_new, cameras_gt.get_camera_center(), cc_pred
```
Now, you could plot your cameras using something like:
```
plot_scene({"scene": {
    "cameras_gt": cameras_gt,
    "cameras_pred": align_cameras(cameras_gt, cameras_pred)[0],
}})
```
Re: data format
We follow [Pytorch3D](https://pytorch3d.org/docs/cameras) camera conventions. You may want to look at the documentation for [PerspectiveCameras](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html#pytorch3d.renderer.cameras.PerspectiveCameras)

The shapes should be: R (N, 3, 3), T (N, 3), focal_length (N, 2), principal_point (N, 2) where the focal_length and principal_point are in NDC. In practice, RelPose++ only cares about the extrinisics, so you really only need the R and T. You should double check that you are converting your ground truth camera representation into Pytorch3D cameras properly.

For training on your data, you probably will want to construct something like `relpose/dataset/co3d_v2.py` since the custom data dataset is only for a single sequence.

**Comment by ttsesm** [comment]
Ciao @jasonyzhang, I was playing a bit with the cameras and I am getting the following results. My guess is that I am doing something wrong, but I am also not sure. I am using vedo in order to plot individually my camera and stuff since for me it is much easier to plot them and debug. Anyways, this is the procedure that I am following. I am transforming my ground truth cameras into the Pytorch3D as follows:
```
from pytorch3d.renderer import FoVPerspectiveCameras
from pytorch3d.renderer.cameras import Translate, Rotate
from pytorch3d.vis.plotly_vis import plot_scene, get_camera_wireframe

import vedo as vd

if torch.cuda.is_available():
    device = torch.device("cuda:0")
else:
    device = torch.device("cpu")
    print("WARNING: CPU only, this will be slow!")


# Compute the optimal scale s, rotation R, and translation t
def align_cameras(cameras_gt, cameras_pred):
    cc_pred, s, R, T = compute_optimal_alignment(
        cameras_gt.get_camera_center(), cameras_pred.get_camera_center()
    )
    T = T.unsqueeze(0)

    cameras_new = FoVPerspectiveCameras(
        R=R.T.unsqueeze(0) @ cameras_pred.R,
        T=s * cameras_pred.T - (T @ R.T @ cameras_pred.R).squeeze(1),
    )

    if torch.isnan(T).any():
        cameras_new.T = torch.zeros_like(cameras_new.T)
    return cameras_new, cameras_gt.get_camera_center(), cc_pred

# Function to visualize the ground truth cameras from the FoVPerspectiveCameras() format
def get_visual_gt_cameras(cameras, scale: float = 0.3, color: str = "blue"):
    cam_wires_canonical = get_camera_wireframe(scale=scale).cuda()[None]

    vd_handles = []
    j = 0
    while j < len(cameras):
        wire = cameras[j]

        tt = Translate(wire.T)._matrix.detach().cpu().numpy().T.astype(float).squeeze()
        rr = Rotate(wire.R)._matrix.detach().cpu().numpy().astype(float).squeeze()
        rr[0:3, 3] = tt[0:3, 3]

        h = cam_wires_canonical.detach().cpu().numpy().T.astype(float).squeeze()
        vd_handles.append(vd.Line(h).apply_transform(rr).color(color))
        j += 1
    return vd_handles

# Function to visualize the estimated cameras from the FoVPerspectiveCameras() format
def get_visual_est_cameras(cameras, scale: float = 0.3, color: str = "blue", inv: int = 0):
    cam_wires_canonical = get_camera_wireframe(scale=scale).cuda()[None]
    if inv:
        cam_trans = cameras.get_world_to_view_transform().inverse()
    else:
        cam_trans = cameras.get_world_to_view_transform()

    cam_wires_trans = cam_trans.transform_points(cam_wires_canonical)

    vd_handles = []
    for wire in cam_wires_trans:
        h = wire.detach().cpu().numpy().T.astype(float)
        vd_handles.append(vd.Line(h).color(color))
    return vd_handles


# Load my cameras from the file....
....
....
....

# Port them to the Pytorch3D format
cameras_gt = FoVPerspectiveCameras(
    R=filtered_cameras_dict['cam2world'][:,0:3,0:3],
    T=filtered_cameras_dict['cam2world'][:,0:3,3],
    K=filtered_cameras_dict['Ks'],
    device=device,
)

# Load my mesh model
mesh = vd.load("model.obj").texture("model.png")

# Get visual wire cameras
gt_cams = get_visual_gt_cameras(cameras_gt, color="green")
pred_cams = get_visual_est_cameras(FoVPerspectiveCameras(R=R_pred_mst, T=T_pred, device=device), scale=0.01, inv=1))
opt_cams = get_visual_est_cameras(FoVPerspectiveCameras(R=R_pred_coord_asc, T=T_pred, device=device), scale=0.01, color="#FF7D1E", inv=1)

# Plot everything together
vd.show(mesh, gt_cams, pred_cams, opt_cams, axes=1, interactive=True).close()
```
The above gives me the following output:
![image](https://github.com/amyxlase/relpose-plus-plus/assets/10189018/777eff00-a175-4c6b-abb3-73d31f0d8c6e)
![image](https://github.com/amyxlase/relpose-plus-plus/assets/10189018/1b24a0c9-c850-42ff-8ceb-07d50261a7ef)
![image](https://github.com/amyxlase/relpose-plus-plus/assets/10189018/4c21d744-08fb-40fc-a8f2-c2ba9f59a917)

which it seems to be giving me the right estimation, of course the gt and estimated poses are in different coordinate system and scale.

Then I tried to align the two sets of camera poses as discussed above by aligning the two coordinate systems:
```
# Get optimal alignment
align_cams = align_cameras(cameras_gt, FoVPerspectiveCameras(R=R_pred_coord_asc, T=T_pred, device=device))[0]

# Get visual wire cameras
finals_cams = get_visual_gt_cameras(align_cams, color="black")

# Plot everything together
vd.show(mesh, gt_cams, final_cams, axes=1, interactive=True).close()
```
However, my output final cams are kind of messed up:
![image](https://github.com/amyxlase/relpose-plus-plus/assets/10189018/48d07619-0cf7-45a9-a576-878098a39a8f)

any idea what I might be doing wrong? My guess is that I am not transforming my gt cameras to the `FoVPerspectiveCameras()` format correctly, but I am not sure.

**Comment by jasonyzhang** [comment]
Could you send me `filtered_cameras_dict` and `mesh.obj`?

**Comment by ttsesm** [comment]
Sure, please find them in the following link: 
https://filesender.garr.it/?s=download&token=742ddeae-0fdb-48e9-bd1d-7028ddd94fe6 

I've also included the images just in case.

**Comment by jasonyzhang** [comment]
Do you know why the rotation matrices in `cam2world` are determinant -1? They appear to be reflection matrices rather than valid rotation matrices.

Ignoring this issue, I attached a notebook that should convert the camera poses from your coordinate system to the [Pytorch3D extrinsics representation (world2cam)](https://pytorch3d.org/docs/cameras). The dashed cameras are the predicted cameras from RelPose++, and the solid cameras are the ground truth ones from your json. The ground truth cameras are currently upside down. I think this could be related to the rotations being reflections?

<img width="469" alt="image" src="https://github.com/amyxlase/relpose-plus-plus/assets/6900167/a69e9bf5-853a-47e2-a47a-a2ab6bd1aa8b">

Hopefully, you will be able to invert these operations to then convert from Pytorch3d camera representation to your representation.

[process_cameras.ipynb](https://github.com/amyxlase/relpose-plus-plus/files/11807551/process.artifact.cameras.txt)

**Comment by ttsesm** [comment]
> Do you know why the rotation matrices in `cam2world` are determinant -1? They appear to be reflection matrices rather than valid rotation matrices.

This is the format that are saved from Metashape, since are obtained through a photogrammetry pipeline. Thus, you need to take the matrix product with the following matrix:
```
opengl2opencv = np.asarray([[-1.,  0.,  0.,  0.],
                            [ 0., -1.,  0.,  0.],
                            [ 0.,  0.,  1.,  0.],
                            [ 0.,  0.,  0.,  1.]], dtype=np.float32)
```
in order to obtain the correct transformation. My bad, that I didn't mentioned it to you. That's also why you get them upside down later on.

To understand a bit better when you apply this transformation:
```
new_R = cam2world[:, :3, :3]
new_T = -cam2world[:, :3, 3:].transpose(1, 2) @ new_R  # -R^-1 @ T
```
you go from world to cam, right?

Thanks a lot for your time ;-).

**Comment by ttsesm** [comment]
Also another question related now to the creation of the dataset. How did you train the masked model?

From what I understand this command [here](https://github.com/amyxlase/relpose-plus-plus#training) is for training the bbox model, right?

**Comment by jasonyzhang** [comment]
I just pushed an update so that it can train with masks. Just add `--mask_images`. Make sure your dataset supports masking images if the flag is set.

**Comment by ttsesm** [comment]
> I just pushed an update so that it can train with masks. Just add `--mask_images`. Make sure your dataset supports masking images if the flag is set.

Thanks ;-)

A clarification question though, you still need to have the bounding boxes of the objects when loading the data for training, right?

Also, can you give me an estimation of the training time for your pre- trained models. I couldn't find any info in the paper about that.

**Comment by jasonyzhang** [comment]
You can compute the bounding boxes by finding the corners of the mask. Since the dataset will need to load the masks anyway at training time, you don't need to pre-process the dataset to compute masks
