### ISSUE TITLE
Camera convention of pose prediction

### ISSUE THREAD

**Issue by Totoro97** [amyxlase/relpose-plus-plus#9]
Hi, thanks a lot for sharing this code! What is the convention of the predicted poses? Is it camera to world poses or world to cameras poses? And what should I do if I want to convert the poses to `camera to world + opencv style`? (i.e., z for the looking direction, y for the down direction and x for the right direction).

Thanks in advance!

**Comment by jasonyzhang** [comment]
Hi, we use world to view using the [Pytorch3D convention](https://pytorch3d.org/docs/cameras) (+X:left, +Y: up and +Z: from us to scene).

Pytorch3D has some [utitilies](https://github.com/facebookresearch/pytorch3d/blob/099fc069fb1113ea8d8dd4063a4cec7dce894118/pytorch3d/renderer/camera_conversions.py#L62) to convert to and from OpenCV camera convention, but I have not personally tested them.

If you have any issues with the conversion, I can take a look at some code. Otherwise, you will likely get more help from the Pytorch3D repo since converting between camera conventions is a commonly raised issue.
